---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: mithril-core
description: Fedora CoreOS with zfs
base-image: quay.io/fedora/fedora-coreos
image-version: 44

cosign-version: none
nushell-version: none

platforms:
  - linux/amd64

modules:
  - type: script
    scripts:
      - installzfskmod.sh
    secrets:
      - type: env
        name: KERNEL_PRIVKEY
        mount:
          type: file
          destination: /tmp/certs/private_key.priv
  - type: files
    source: ghcr.io/blue-build/modules@sha256:c5ed99f07b15c8d575a4fa64a77e5cd5602b00da4c84379f5675db2ae4757061
    files:
      - source: system/zfs
        destination: /

  - type: signing
